FROM picarx-ros:rolling

# Motor-specific: ensure correct lgpio version is pip-installed
# (overrides the apt version which may behave differently)
# RUN apt update && apt install -y python3-pip python3-lgpio python3-pigpio python3-rpi.gpio
# RUN pip3 install gpiozero --break-system-packages
RUN pip3 install --break-system-packages --upgrade \
    lgpio \
    gpiozero

# Force the container user into the gpio group
RUN groupadd -f gpio && usermod -aG gpio root

WORKDIR /ws
CMD ["bash"]
